### ISSUE TITLE
fuzzy-fireant-2

### ISSUE THREAD

**Issue by ZiYi0414** [ZiYi0414/handsome-css3-lib#38]
---
title: fuzzy-fireant-2
made_by: Custyyyy
---

```css
#bottone1 {
  padding-left: 33px;
  padding-right: 33px;
  padding-bottom: 16px;
  padding-top: 16px;
  border-radius: 9px;
  background: #d5f365;
  border: none;
  font-family: inherit;
  text-align: center;
  cursor: pointer;
  transition: 0.4s;
}

#bottone1:hover {
  box-shadow: 7px 5px 56px -14px #c3d900;
}

#bottone1:active {
  transform: scale(0.97);
  box-shadow: 7px 5px 56px -10px #c3d900;
}
```

```html
<button id="bottone1"><strong>Discover features</strong></button>
```
