### ISSUE TITLE
giant-donkey-36

### ISSUE THREAD

**Issue by ZiYi0414** [ZiYi0414/handsome-css3-lib#39]
---
title: giant-donkey-36
made_by: adamgiebl
---

```css
button {
  background: #fbca1f;
  font-family: inherit;
  padding: 0.6em 1.3em;
  font-weight: 900;
  font-size: 18px;
  border: 3px solid black;
  border-radius: 0.4em;
  box-shadow: 0.1em 0.1em;
}

button:hover {
  transform: translate(-0.05em, -0.05em);
  box-shadow: 0.15em 0.15em;
}

button:active {
  transform: translate(0.05em, 0.05em);
  box-shadow: 0.05em 0.05em;
}
```

```html
<button>Button</button>
```
