### ISSUE TITLE
modern-dragon-25

### ISSUE THREAD

**Issue by ZiYi0414** [ZiYi0414/handsome-css3-lib#41]
---
title: modern-dragon-25
made_by: JasonMep
---

```css
.button {
  color: #ecf0f1;
  font-size: 17px;
  background-color: #e67e22;
  border: 1px solid #f39c12;
  border-radius: 5px;
  padding: 10px;
  box-shadow: 0px 6px 0px #d35400;
  transition: all 0.1s;
}

.button:active {
  box-shadow: 0px 2px 0px #d35400;
  position: relative;
  top: 2px;
}
```

```html
<button class="button">Click Here</button>
```
