### ISSUE TITLE
purple-rat-85

### ISSUE THREAD

**Issue by ZiYi0414** [ZiYi0414/handsome-css3-lib#45]
---
title: purple-rat-85
made_by: satyamchaudharydev
---

```css
button {
  --bg: #e74c3c;
  --text-color: #fff;
  position: relative;
  width: 150px;
  border: none;
  background: var(--bg);
  color: var(--text-color);
  padding: 1em;
  font-weight: bold;
  text-transform: uppercase;
  transition: 0.2s;
  border-radius: 5px;
  opacity: 0.8;
  letter-spacing: 1px;
  box-shadow: #c0392b 0px 7px 2px, #000 0px 8px 5px;
}

button:hover {
  opacity: 1;
}

button:active {
  top: 4px;
  box-shadow: #c0392b 0px 3px 2px, #000 0px 3px 5px;
}
```

```html
<button>Click me</button>
```
