### ISSUE TITLE
[button]silent-kangaroo-88

### ISSUE THREAD

**Issue by ZiYi0414** [ZiYi0414/handsome-css3-lib#51]
---
title: silent-kangaroo-88
made_by: mobinkakei
---

```css
button {
  position: relative;
  margin: 0;
  padding: 17px 35px;
  outline: none;
  text-decoration: none;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-pack: center;
  -ms-flex-pack: center;
  justify-content: center;
  -webkit-box-align: center;
  -ms-flex-align: center;
  align-items: center;
  cursor: pointer;
  text-transform: uppercase;
  background-color: #fff;
  border: 1px solid rgba(22, 76, 167, 0.6);
  border-radius: 10px;
  color: #1d89ff;
  font-weight: 400;
  font-family: inherit;
  z-index: 0;
  overflow: hidden;
  -webkit-transition: all 0.3s cubic-bezier(0.02, 0.01, 0.47, 1);
  transition: all 0.3s cubic-bezier(0.02, 0.01, 0.47, 1);
}

button span {
  color: #164ca7;
  font-size: 14px;
  font-weight: 500;
  letter-spacing: 0.7px;
}

button:hover {
  -webkit-animation: rotate624 0.7s ease-in-out both;
  animation: rotate624 0.7s ease-in-out both;
}

button:hover span {
  -webkit-animation: storm1261 0.7s ease-in-out both;
  animation: storm1261 0.7s ease-in-out both;
  -webkit-animation-delay: 0.06s;
  animation-delay: 0.06s;
}

@-webkit-keyframes rotate624 {
  0% {
    -webkit-transform: rotate(0deg) translate3d(0, 0, 0);
    transform: rotate(0deg) translate3d(0, 0, 0);
  }

  25% {
    -webkit-transform: rotate(3deg) translate3d(0, 0, 0);
    transform: rotate(3deg) translate3d(0, 0, 0);
  }

  50% {
    -webkit-transform: rotate(-3deg) translate3d(0, 0, 0);
    transform: rotate(-3deg) translate3d(0, 0, 0);
  }

  75% {
    -webkit-transform: rotate(1deg) translate3d(0, 0, 0);
    transform: rotate(1deg) translate3d(0, 0, 0);
  }

  100% {
    -webkit-transform: rotate(0deg) translate3d(0, 0, 0);
    transform: rotate(0deg) translate3d(0, 0, 0);
  }
}

@keyframes rotate624 {
  0% {
    -webkit-transform: rotate(0deg) translate3d(0, 0, 0);
    transform: rotate(0deg) translate3d(0, 0, 0);
  }

  25% {
    -webkit-transform: rotate(3deg) translate3d(0, 0, 0);
    transform: rotate(3deg) translate3d(0, 0, 0);
  }

  50% {
    -webkit-transform: rotate(-3deg) translate3d(0, 0, 0);
    transform: rotate(-3deg) translate3d(0, 0, 0);
  }

  75% {
    -webkit-transform: rotate(1deg) translate3d(0, 0, 0);
    transform: rotate(1deg) translate3d(0, 0, 0);
  }

  100% {
    -webkit-transform: rotate(0deg) translate3d(0, 0, 0);
    transform: rotate(0deg) translate3d(0, 0, 0);
  }
}

@-webkit-keyframes storm1261 {
  0% {
    -webkit-transform: translate3d(0, 0, 0) translateZ(0);
    transform: translate3d(0, 0, 0) translateZ(0);
  }

  25% {
    -webkit-transform: translate3d(4px, 0, 0) translateZ(0);
    transform: translate3d(4px, 0, 0) translateZ(0);
  }

  50% {
    -webkit-transform: translate3d(-3px, 0, 0) translateZ(0);
    transform: translate3d(-3px, 0, 0) translateZ(0);
  }

  75% {
    -webkit-transform: translate3d(2px, 0, 0) translateZ(0);
    transform: translate3d(2px, 0, 0) translateZ(0);
  }

  100% {
    -webkit-transform: translate3d(0, 0, 0) translateZ(0);
    transform: translate3d(0, 0, 0) translateZ(0);
  }
}

@keyframes storm1261 {
  0% {
    -webkit-transform: translate3d(0, 0, 0) translateZ(0);
    transform: translate3d(0, 0, 0) translateZ(0);
  }

  25% {
    -webkit-transform: translate3d(4px, 0, 0) translateZ(0);
    transform: translate3d(4px, 0, 0) translateZ(0);
  }

  50% {
    -webkit-transform: translate3d(-3px, 0, 0) translateZ(0);
    transform: translate3d(-3px, 0, 0) translateZ(0);
  }

  75% {
    -webkit-transform: translate3d(2px, 0, 0) translateZ(0);
    transform: translate3d(2px, 0, 0) translateZ(0);
  }

  100% {
    -webkit-transform: translate3d(0, 0, 0) translateZ(0);
    transform: translate3d(0, 0, 0) translateZ(0);
  }
}

.btn-shine {
  border: 1px solid;
  overflow: hidden;
  position: relative;
}

.btn-shine span {
  z-index: 20;
}

.btn-shine:after {
  background: #38ef7d;
  content: '';
  height: 155px;
  left: -75px;
  opacity: 0.4;
  position: absolute;
  top: -50px;
  -webkit-transform: rotate(35deg);
  -ms-transform: rotate(35deg);
  transform: rotate(35deg);
  -webkit-transition: all 550ms cubic-bezier(0.19, 1, 0.22, 1);
  transition: all 550ms cubic-bezier(0.19, 1, 0.22, 1);
  width: 50px;
  z-index: -10;
}

.btn-shine:hover:after {
  left: 120%;
  -webkit-transition: all 550ms cubic-bezier(0.19, 1, 0.22, 1);
  transition: all 550ms cubic-bezier(0.19, 1, 0.22, 1);
}
```

```html
<button class="btn-shine">
  <span>Shine</span>
</button>
```
