### ISSUE TITLE
[button]young-eagle-60

### ISSUE THREAD

**Issue by ZiYi0414** [ZiYi0414/handsome-css3-lib#59]
---
title: young-eagle-60
made_by: gksckt
theme: dark
---

```css
button {
  background-color: #444141;
  border-radius: 4px;
  color: #fff;
  cursor: pointer;
  padding: 15px 30px;
  font-size: 18px;
  font-weight: bold;
  letter-spacing: 1px;
  border: none;
}

button:hover {
  background-image: linear-gradient(
    90deg,
    #53cbef 0%,
    #dcc66c 50%,
    #ffa3b6 75%,
    #53cbef 100%
  );
  animation: slidernbw 5s linear infinite;
  color: #000;
}

@keyframes slidernbw {
  to {
    background-position: 20vw;
  }
}
```

```html
<button>Button</button>
```
